name: "test"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          # - macos-latest # Apple bravo
          - ubuntu-latest

    name: "cargo nextest"
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Setup nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo nextest
        run: cargo nextest run
